databases:
  - name: doctor_appointment
    databaseName: doctor_appointment
    user: doctor_appointment_c1zb_user

services:
  - type: web
    name: appointment-doctor
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: doctor_appointment
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false